spring:
  application:
    name: FILE-UPLOAD-SERVICE
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

server:
  servlet:
    context-path: /file-upload-service
  port: ${PORT:0}